### ISSUE TITLE
Frontend node scripts on Windows doesn't work

### ISSUE THREAD

**Issue by dp46504** [MLH-Fellowship/SocioMark#122]
Running npm start  on frontend on Windows doesn't work
Changing npm start script to:
SET NODE_ENV=development craco start
didn't do much. 

(https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman)

**Comment by aitikgupta** [comment]
~@dp46504 can you try out the linked PR? https://github.com/MLH-Fellowship/SocioMark/pull/123~

~Let me know if that is working or not, I haven't tested it out because I don't have an immediate access to a Windows machine.~

@DebugAgrawal and @bodhisha have confirmed this works on their Windows machines.
